products = [
    {
        "_id": 0,
        "name": "coca cola",
        "qty": 20,
        "category": 0,
        "price": 25,
        "rating": 4.9,
        "image": "/images/cola.jpg",
        "description": "Refreshing drink",
    },
    {
        "_id": 1,
        "name": "pepsi",
        "qty": 20,
        "category": 0,
        "price": 25,
        "rating": 4.9,
        "image": "/images/cola.jpg",
        "description": "Refreshing drink",
    },
    {
        "_id": 2,
        "name": "water",
        "qty": 20,
        "category": 0,
        "price": 25,
        "rating": 4.9,
        "image": "/images/water.jpg",
        "description": "Refreshing drink",
    },
    {
        "_id": 3,
        "name": "hamburger",
        "qty": 40,
        "category": 1,
        "price": 95,
        "rating": 4.9,
        "image": "/images/burger.jpg",
        "description": "American Burger",
    },
    {
        "_id": 4,
        "name": "fries",
        "qty": 20,
        "category": 1,
        "price": 45,
        "rating": 4.9,
        "image": "/images/fries.jpg",
        "description": "American fast-food",
    },
    {
        "_id": 5,
        "name": "pizza",
        "qty": 20,
        "category": 1,
        "price": 120,
        "rating": 4.9,
        "image": "/images/pizza.jpg",
        "description": "Italian meal",
    },
    {
        "_id": 6,
        "name": "pide",
        "qty": 20,
        "category": 1,
        "price": 89,
        "rating": 4.2,
        "image": "/images/pide.jpg",
        "description": "Turkih Cuisine",
    },
]
