# Generated by Django 4.1.7 on 2023-04-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_customerprofile_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.businessprofile",
            ),
        ),
    ]
